Repository neophyte-programmer/dsa-solutions, pull requests merged in 2022-11, with the labels that each got.

#15 Solve new Hackerrank challenge
  hackerrank/reverse-array-ts/README.md
  hackerrank/reverse-array-ts/index.ts
Labels: NEW, TypeScript

#16 Qbentil: ## Hackerrank - 30 Days of Code > Binary Numbers
  hackerrank/binary-numbers-ts/README.md
  hackerrank/binary-numbers-ts/index.ts
Labels: NEW, TypeScript

#18 LeetCode - Absolute K Diff TS
  leetcode/absolute-k-diff-ts/README.md
  leetcode/absolute-k-diff-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#17 Revert "Qbentil: Hackerrank - 30 Days of Code > Binary Numbers"
  hackerrank/binary-numbers-ts/README.md
  hackerrank/binary-numbers-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#21 LEETCODE - REVERSE VOWELS IN A STRING - TS
  README.md
  hackerrank/binary-numbers-ts/README.md
  hackerrank/binary-numbers-ts/index.ts
  leetcode/reverse-vowels-ts/README.md
  leetcode/reverse-vowels-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#22 LEETCODE - Reverse Integer - TypeScript
  leetcode/reverse-integer-ts/README.md
  leetcode/reverse-integer-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#23 LEETCODE - Orderly Queue - TypeScript
  leetcode/house-robber-ts/README.md
  leetcode/house-robber-ts/index.ts
  leetcode/orderly-queue-ts/README.md
  leetcode/orderly-queue-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#24 LEETCODE - 1323. Maximum 69 Number - TypeScript
  leetcode/maximu-69-number-ts/README.md
  leetcode/maximu-69-number-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#28 LeetCode - Two Sum - TS / UPDATED
  leetcode/two-sum-ts/index.ts
Labels: UPDATE, READY FOR REVIEW, TypeScript

#29 HackerRank - Print Elements of a Linked List - JavaScript
  hackerrank/print-elements-of-linkedlist-js/README.md
  hackerrank/print-elements-of-linkedlist-js/index.js
  leetcode/two-sum-ts/README.md
  leetcode/two-sum-ts/index.ts
Labels: READY FOR REVIEW, NEW, JavaScript

#30 HackerRank - LinkedList-addto-tail-js
  hackerrank/LinkedList-addto-tail-js/README.md
  hackerrank/LinkedList-addto-tail-js/index.js
  hackerrank/print-elements-of-linkedlist-js/README.md
  hackerrank/print-elements-of-linkedlist-js/index.js
  leetcode/house-robber-ts/README.md
  leetcode/house-robber-ts/index.ts
  leetcode/maximu-69-number-ts/README.md
  leetcode/maximu-69-number-ts/index.ts
  leetcode/orderly-queue-ts/README.md
  leetcode/orderly-queue-ts/index.ts
  leetcode/reverse-integer-ts/README.md
  leetcode/reverse-integer-ts/index.ts
  leetcode/reverse-vowels-ts/README.md
  leetcode/reverse-vowels-ts/index.ts
  leetcode/two-sum-ts/README.md
  leetcode/two-sum-ts/index.ts
Labels: READY FOR REVIEW, NEW, JavaScript

#33 HackerRank - LinkedList-addto-Head-JS
  hackerrank/Insert-to-head-js/README.md
  hackerrank/Insert-to-head-js/index.js
Labels: READY FOR REVIEW, NEW, JavaScript

#34 LEETCODE 125. Valid Palindrome - TypeScript
  leetcode/valid-palindrome-ts/README.md
  leetcode/valid-palindrome-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#27 Leetcode Sort Sentence JS
  leetcode/How Many Numbers Are Smaller Than the Current Number-js/README.md
  leetcode/How Many Numbers Are Smaller Than the Current Number-js/index.js
  leetcode/Sorting the Sentence-js/README.md
  leetcode/Sorting the Sentence-js/index.js
Labels: REVIEWING, can't merge, NEW, JavaScript

#40 Leetcode - 234. PALINDROME LINKED LIST
  leetcode/Palindrome-LinkedList-ts/README.md
  leetcode/Palindrome-LinkedList-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#41 LEETCODE 4. Median of Two Sorted Arrays
  leetcode/median-sorted-arr-ts/README.md
  leetcode/median-sorted-arr-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript

#42 3. Longest Substring Without Repeating Characters
  leetcode/substring-without-rep-ts/README.md
  leetcode/substring-without-rep-ts/index.ts
Labels: READY FOR REVIEW, NEW, TypeScript
