Repository neophyte-programmer/dsa-solutions, pull requests merged in 2022-10, with the labels that each got.

#7 Qbentil codesdpace: Quick updates on Readme
  README.md
  edabit/add-single-number-ts/README.md
  edabit/add-single-number-ts/index.ts
  edabit/match-houses-ts/README.md
  edabit/match-houses-ts/image.png
  edabit/match-houses-ts/index.ts
Labels: UPDATE, READY FOR REVIEW

#8 [Leetcode] Move Zeroes Javascript
  leetcode/move-zeroes-js/README.md
  leetcode/move-zeroes-js/index.js
Labels: REVIEWING, NEW, JavaScript

#10 Leetcode Palindrome number JS
  leetcode/palindrome-number-js/README.md
  leetcode/palindrome-number-js/index.js
Labels: READY FOR REVIEW, NEW, JavaScript

#12 Leetcode Plus One JS
  leetcode/plus-one-js/README.md
  leetcode/plus-one-js/index.js
Labels: READY FOR REVIEW, REVIEWING, JavaScript
